spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/otproject?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: asdf
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

