
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/otproject?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: sql_server
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password:
    key-store-type: PKCS12